std::string Ammo = "[\n"
                         "  {\n"
                         "    \"Category\": \"Ammo\",\n"
                         "    \"Items\": [\n"
                         "      {\n"
                         "        \"itemId\": 301001,\n"
                         "        \"itemClass\": \"BP_Ammo_9mm_Pickup_C_1\",\n"
                         "        \"itemName\": \"9mm\",\n"
                         "        \"itemTextColor\": \"0xFF919AFF\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 302001,\n"
                         "        \"itemClass\": \"BP_Ammo_762mm_Pickup_C_1\",\n"
                         "        \"itemName\": \"7.62mm\",\n"
                         "        \"itemTextColor\": \"0xFFFCC89D\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 303001,\n"
                         "        \"itemClass\": \"BP_Ammo_556mm_Pickup_C_1\",\n"
                         "        \"itemName\": \"5.56mm\",\n"
                         "        \"itemTextColor\": \"0xFFD1EEEE\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 304001,\n"
                         "        \"itemClass\": \"BP_Ammo_12Guage_Pickup_C_1\",\n"
                         "        \"itemName\": \"12 Gauge\",\n"
                         "        \"itemTextColor\": \"0xFFFF66C9\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 305001,\n"
                         "        \"itemClass\": \"BP_Ammo_45ACP_Pickup_C_1\",\n"
                         "        \"itemName\": \".45 ACP\",\n"
                         "        \"itemTextColor\": \"0xFFF8FAB9\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 306001,\n"
                         "        \"itemClass\": \"BP_Ammo_300Magnum_Pickup_C_1\",\n"
                         "        \"itemName\": \".300 Magnum\",\n"
                         "        \"itemTextColor\": \"0xFFFF66C9\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 307001,\n"
                         "        \"itemClass\": \"BP_Ammo_Bolt_Pickup_C_1\",\n"
                         "        \"itemName\": \"Bolt\",\n"
                         "        \"itemTextColor\": \"0xFFFF66C9\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      }\n"
                         "    ]\n"
                         "  }\n"
                         "]";