std::string Armor = "[\n"
                         "  {\n"
                         "    \"Category\": \"Bag\",\n"
                         "    \"Items\": [\n"
                         "      {\n"
                         "        \"itemId\": 501006,\n"
                         "        \"itemClass\": \"PickUp_BP_Bag_Lv3_B_C_1\",\n"
                         "        \"itemName\": \"Backpack (Lv. 3)\",\n"
                         "        \"itemTextColor\": \"0xFFFFF266\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 502002,\n"
                         "        \"itemClass\": \"PickUp_BP_Helmet_Lv2_C_1\",\n"
                         "        \"itemName\": \"Military Helmet (Lv. 2)\",\n"
                         "        \"itemTextColor\": \"0xFFFFF266\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 502003,\n"
                         "        \"itemClass\": \"PickUp_BP_Helmet_Lv3_C_1\",\n"
                         "        \"itemName\": \"Spetsnaz Helmet (Lv. 3)\",\n"
                         "        \"itemTextColor\": \"0xFFFFF266\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 503002,\n"
                         "        \"itemClass\": \"PickUp_BP_Armor_Lv2_C_1\",\n"
                         "        \"itemName\": \"Police Vest (Lv. 2)\",\n"
                         "        \"itemTextColor\": \"0xFFFFF266\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 503003,\n"
                         "        \"itemClass\": \"PickUp_BP_Armor_Lv3_C_1\",\n"
                         "        \"itemName\": \"Military Vest (Lv. 3)\",\n"
                         "        \"itemTextColor\": \"0xFFFFF266\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      }\n"
                         "    ]\n"
                         "  }\n"
                         "]";