std::string Atta = "[\n"
                         "  {\n"
                         "    \"Category\": \"Attachment\",\n"
                         "    \"Items\": [\n"
                         "      {\n"
                         "        \"itemId\": 202007,\n"
                         "        \"itemClass\": \"BP_WB_Lasersight_Pickup_C_1\",\n"
                         "        \"itemName\": \"Laser Sight\",\n"
                         "        \"itemTextColor\": \"0xFF9FBD1C\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 203005,\n"
                         "        \"itemClass\": \"BP_MZJ_8X_Pickup_C_1\",\n"
                         "        \"itemName\": \"8x Scope\",\n"
                         "        \"itemTextColor\": \"0xFF9FBD1C\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 203018,\n"
                         "        \"itemClass\": \"BP_MZJ_SideRMR_Pickup_C_1\",\n"
                         "        \"itemName\": \"Canted Sight\",\n"
                         "        \"itemTextColor\": \"0xFF9FBD1C\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 204014,\n"
                         "        \"itemClass\": \"BP_ZDD_Sniper_Pickup_C_1\",\n"
                         "        \"itemName\": \"Bullet Loop (Sniper Rifles)\",\n"
                         "        \"itemTextColor\": \"0xFFFF66C9\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 205001,\n"
                         "        \"itemClass\": \"BP_QT_UZI_Pickup_C_1\",\n"
                         "        \"itemName\": \"Stock (Micro UZI)\",\n"
                         "        \"itemTextColor\": \"0xFF919AFF\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 205002,\n"
                         "        \"itemClass\": \"BP_QT_A_Pickup_C_1\",\n"
                         "        \"itemName\": \"Tactical Stock (Rifles, SMG)\",\n"
                         "        \"itemTextColor\": \"0xFF9FBD1C\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 205003,\n"
                         "        \"itemClass\": \"BP_QT_Sniper_Pickup_C_1\",\n"
                         "        \"itemName\": \"Cheek Pad (Snipers)\",\n"
                         "        \"itemTextColor\": \"0xFF9FBD1C\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 106001,\n"
                         "        \"itemClass\": \"BP_Pistol_P92_Wrapper_C_1\",\n"
                         "        \"itemName\": \"P92\",\n"
                         "        \"itemTextColor\": \"0xFF919AFF\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 106002,\n"
                         "        \"itemClass\": \"BP_Pistol_P1911_Wrapper_C_1\",\n"
                         "        \"itemName\": \"P1911\",\n"
                         "        \"itemTextColor\": \"0xFFF8FAB9\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 106003,\n"
                         "        \"itemClass\": \"BP_Pistol_R1895_Wrapper_C_1\",\n"
                         "        \"itemName\": \"R1895\",\n"
                         "        \"itemTextColor\": \"0xFFFCC89D\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 106004,\n"
                         "        \"itemClass\": \"BP_Pistol_P18C_Wrapper_C_1\",\n"
                         "        \"itemName\": \"P18C\",\n"
                         "        \"itemTextColor\": \"0xFFFCC89D\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 106005,\n"
                         "        \"itemClass\": \"BP_Pistol_R45_Wrapper_C_1\",\n"
                         "        \"itemName\": \"R45\",\n"
                         "        \"itemTextColor\": \"0xFFF8FAB9\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 106008,\n"
                         "        \"itemClass\": \"BP_Pistol_Vz61_Wrapper_C_1\",\n"
                         "        \"itemName\": \"Vz61\",\n"
                         "        \"itemTextColor\": \"0xFFFCC89D\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 106010,\n"
                         "        \"itemClass\": \"BP_Pistol_DesertEagle_Wrapper_C_1\",\n"
                         "        \"itemName\": \"Desert Eagle\",\n"
                         "        \"itemTextColor\": \"0xFFF8FAB9\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 205004,\n"
                         "        \"itemClass\": \"BP_ZDD_Crossbow_Q_Pickup_C_1\",\n"
                         "        \"itemName\": \"Quiver (Crossbow)\",\n"
                         "        \"itemTextColor\": \"0xFF9FBD1C\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      }\n"
                         "    ]\n"
                         "  }\n"
                         "]";