std::string Grenade = "[\n"
                         "  {\n"
                         "    \"Category\": \"Throwable\",\n"
                         "    \"Items\": [\n"
                         "      {\n"
                         "        \"itemId\": 602002,\n"
                         "        \"itemClass\": \"BP_Grenade_Smoke_Weapon_Wrapper_C_1\",\n"
                         "        \"itemName\": \"Smoke\",\n"
                         "        \"itemTextColor\": \"0xFFD1EEEE\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 602003,\n"
                         "        \"itemClass\": \"BP_Grenade_Burn_Weapon_Wrapper_C\",\n"
                         "        \"itemName\": \"Molotov\",\n"
                         "        \"itemTextColor\": \"0xFFD1EEEE\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 602004,\n"
                         "        \"itemClass\": \"BP_Grenade_Shoulei_Weapon_Wrapper_C_1\",\n"
                         "        \"itemName\": \"Grenade\",\n"
                         "        \"itemTextColor\": \"0xFFD1EEEE\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      }\n"
                         "    ]\n"
                         "  }\n"
                         "]";