std::string Mag = "[\n"
                         "  {\n"
                         "    \"Category\": \"Mag\",\n"
                         "    \"Items\": [\n"
                         "      {\n"
                         "        \"itemId\": 204004,\n"
                         "        \"itemClass\": \"BP_DJ_Mid_E_Pickup_C_1\",\n"
                         "        \"itemName\": \"Extended Mag (SMG, Pistols)\",\n"
                         "        \"itemTextColor\": \"0xFF9FBD1C\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 204005,\n"
                         "        \"itemClass\": \"BP_DJ_Mid_Q_Pickup_C_1\",\n"
                         "        \"itemName\": \"Quickdraw Mag (SMG, Pistols)\",\n"
                         "        \"itemTextColor\": \"0xFF9FBD1C\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 204006,\n"
                         "        \"itemClass\": \"BP_DJ_Mid_EQ_Pickup_C_1\",\n"
                         "        \"itemName\": \"Mag (SMG, Pistols)\",\n"
                         "        \"itemTextColor\": \"0xFF9FBD1C\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 204007,\n"
                         "        \"itemClass\": \"BP_DJ_Sniper_E_Pickup_C_1\",\n"
                         "        \"itemName\": \"Extended Mag (Snipers)\",\n"
                         "        \"itemTextColor\": \"0xFF9FBD1C\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 204008,\n"
                         "        \"itemClass\": \"BP_DJ_Sniper_Q_Pickup_C_1\",\n"
                         "        \"itemName\": \"Quickdraw Mag (Snipers)\",\n"
                         "        \"itemTextColor\": \"0xFF9FBD1C\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 204009,\n"
                         "        \"itemClass\": \"BP_DJ_Sniper_EQ_Pickup_C_1\",\n"
                         "        \"itemName\": \"Extended Quickdraw Mag (Snipers)\",\n"
                         "        \"itemTextColor\": \"0xFF9FBD1C\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 204011,\n"
                         "        \"itemClass\": \"BP_DJ_Large_E_Pickup_C_1\",\n"
                         "        \"itemName\": \"Extended Quickdraw Mag (AR)\",\n"
                         "        \"itemTextColor\": \"0xFF9FBD1C\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      }\n"
                         "    ]\n"
                         "  }\n"
                         "]";