std::string Medic = "[\n"
                         "  {\n"
                         "    \"Category\": \"Medic\",\n"
                         "    \"Items\": [\n"
                         "      {\n"
                         "        \"itemId\": 601001,\n"
                         "        \"itemClass\": \"Drink_Pickup_C_1\",\n"
                         "        \"itemName\": \"Energy Drink\",\n"
                         "        \"itemTextColor\": \"0xFF4DFF76\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 601002,\n"
                         "        \"itemClass\": \"Injection_Pickup_C_1\",\n"
                         "        \"itemName\": \"Adrenaline Syringe\",\n"
                         "        \"itemTextColor\": \"0xFF4DFF76\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 601003,\n"
                         "        \"itemClass\": \"Pills_Pickup_C_1\",\n"
                         "        \"itemName\": \"Painkiller\",\n"
                         "        \"itemTextColor\": \"0xFF4DFF76\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 601004,\n"
                         "        \"itemClass\": \"Bandage_Pickup_C_1\",\n"
                         "        \"itemName\": \"Bandage\",\n"
                         "        \"itemTextColor\": \"0xFF4DFF76\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 601005,\n"
                         "        \"itemClass\": \"Firstaid_Pickup_C_1\",\n"
                         "        \"itemName\": \"First Aid Kit\",\n"
                         "        \"itemTextColor\": \"0xFF4DFF76\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 601006,\n"
                         "        \"itemClass\": \"FirstAidbox_Pickup_C_1\",\n"
                         "        \"itemName\": \"Med Kit\",\n"
                         "        \"itemTextColor\": \"0xFF4DFF76\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      }\n"
                         "    ]\n"
                         "  }\n"
                         "]";