std::string Rifle = "[\n"
                         "  {\n"
                         "    \"Category\": \"Rifle\",\n"
                         "    \"Items\": [\n"
                         "      {\n"
                         "        \"itemId\": 101001,\n"
                         "        \"itemClass\": \"BP_Rifle_AKM_Wrapper_C_1\",\n"
                         "        \"itemName\": \"AKM\",\n"
                         "        \"itemTextColor\": \"0xFFFCC89D\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 101002,\n"
                         "        \"itemClass\": \"BP_Rifle_M16A4_Wrapper_C_1\",\n"
                         "        \"itemName\": \"M16A4\",\n"
                         "        \"itemTextColor\": \"0xFFD1EEEE\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 101003,\n"
                         "        \"itemClass\": \"BP_Rifle_SCAR_Wrapper_C_1\",\n"
                         "        \"itemName\": \"SCAR-L\",\n"
                         "        \"itemTextColor\": \"0xFFD1EEEE\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 101004,\n"
                         "        \"itemClass\": \"BP_Rifle_M416_Wrapper_C_1\",\n"
                         "        \"itemName\": \"M416\",\n"
                         "        \"itemTextColor\": \"0xFFD1EEEE\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 101005,\n"
                         "        \"itemClass\": \"BP_Rifle_Groza_Wrapper_C_1\",\n"
                         "        \"itemName\": \"Groza\",\n"
                         "        \"itemTextColor\": \"0xFFFCC89D\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 101006,\n"
                         "        \"itemClass\": \"BP_Rifle_AUG_Wrapper_C_1\",\n"
                         "        \"itemName\": \"AUG A3\",\n"
                         "        \"itemTextColor\": \"0xFFD1EEEE\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 101007,\n"
                         "        \"itemClass\": \"BP_Rifle_QBZ_Wrapper_C_1\",\n"
                         "        \"itemName\": \"QBZ\",\n"
                         "        \"itemTextColor\": \"0xFFD1EEEE\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 101008,\n"
                         "        \"itemClass\": \"BP_Rifle_M762_Wrapper_C_1\",\n"
                         "        \"itemName\": \"M762\",\n"
                         "        \"itemTextColor\": \"0xFFFCC89D\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 101009,\n"
                         "        \"itemClass\": \"BP_Rifle_Mk47_Wrapper_C_1\",\n"
                         "        \"itemName\": \"Mk47 Mutant\",\n"
                         "        \"itemTextColor\": \"0xFFFCC89D\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 101010,\n"
                         "        \"itemClass\": \"BP_Rifle_G36_Wrapper_C_1\",\n"
                         "        \"itemName\": \"G36C\",\n"
                         "        \"itemTextColor\": \"0xFFD1EEEE\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 101100,\n"
                         "        \"itemClass\": \"BP_Rifle_FAMAS_Wrapper_C_1\",\n"
                         "        \"itemName\": \"FAMAS\",\n"
                         "        \"itemTextColor\": \"0xFFD1EEEE\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 105001,\n"
                         "        \"itemClass\": \"BP_Other_M249_Wrapper_C_1\",\n"
                         "        \"itemName\": \"M249\",\n"
                         "        \"itemTextColor\": \"0xFFD1EEEE\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 105002,\n"
                         "        \"itemClass\": \"BP_Other_DP28_Wrapper_C_1\",\n"
                         "        \"itemName\": \"DP-28\",\n"
                         "        \"itemTextColor\": \"0xFFFCC89D\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      }\n"
                         "    ]\n"
                         "  }\n"
                         "]";