std::string Scope = "[\n"
                         "  {\n"
                         "    \"Category\": \"scope\",\n"
                         "    \"Items\": [\n"
                         "      {\n"
                         "        \"itemId\": 203001,\n"
                         "        \"itemClass\": \"BP_MZJ_HD_Pickup_C_1\",\n"
                         "        \"itemName\": \"Red Dot Sight\",\n"
                         "        \"itemTextColor\": \"0xFF9FBD1C\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 203003,\n"
                         "        \"itemClass\": \"BP_MZJ_2X_Pickup_C_1\",\n"
                         "        \"itemName\": \"2x Scope\",\n"
                         "        \"itemTextColor\": \"0xFF9FBD1C\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 203014,\n"
                         "        \"itemClass\": \"BP_MZJ_3X_Pickup_C_1\",\n"
                         "        \"itemName\": \"3x Scope\",\n"
                         "        \"itemTextColor\": \"0xFF9FBD1C\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 203004,\n"
                         "        \"itemClass\": \"BP_MZJ_4X_Pickup_C_1\",\n"
                         "        \"itemName\": \"4x Scope\",\n"
                         "        \"itemTextColor\": \"0xFF9FBD1C\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 203015,\n"
                         "        \"itemClass\": \"BP_MZJ_6X_Pickup_C_1\",\n"
                         "        \"itemName\": \"6x Scope\",\n"
                         "        \"itemTextColor\": \"0xFF9FBD1C\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      }\n"
                         "    ]\n"
                         "  }\n"
                         "]";