std::string Sniper = "[\n"
                         "  {\n"
                         "    \"Category\": \"Sniper\",\n"
                         "    \"Items\": [\n"
                         "      {\n"
                         "        \"itemId\": 103001,\n"
                         "        \"itemClass\": \"BP_Sniper_Kar98k_Wrapper_C_1\",\n"
                         "        \"itemName\": \"Kar98K\",\n"
                         "        \"itemTextColor\": \"0xFFFCC89D\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 103002,\n"
                         "        \"itemClass\": \"BP_Sniper_M24_Wrapper_C_1\",\n"
                         "        \"itemName\": \"M24\",\n"
                         "        \"itemTextColor\": \"0xFFFCC89D\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 103003,\n"
                         "        \"itemClass\": \"BP_Sniper_AWM_Wrapper_C_1\",\n"
                         "        \"itemName\": \"AWM\",\n"
                         "        \"itemTextColor\": \"0xFFFF66C9\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 103006,\n"
                         "        \"itemClass\": \"BP_Sniper_Mini14_Wrapper_C_1\",\n"
                         "        \"itemName\": \"Mini14\",\n"
                         "        \"itemTextColor\": \"0xFFD1EEEE\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 103007,\n"
                         "        \"itemClass\": \"BP_WEP_Mk14_Pickup_C_1\",\n"
                         "        \"itemName\": \"Mk14\",\n"
                         "        \"itemTextColor\": \"0xFFFCC89D\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 103011,\n"
                         "        \"itemClass\": \"BP_Sniper_Mosin_Wrapper_C_1\",\n"
                         "        \"itemName\": \"Mosin Nagant Sniper Rifle\",\n"
                         "        \"itemTextColor\": \"0xFFFCC89D\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 103100,\n"
                         "        \"itemClass\": \"BP_Sniper_MK12_Wrapper_C_1\",\n"
                         "        \"itemName\": \"Mk12\",\n"
                         "        \"itemTextColor\": \"0xFFFCC89D\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      }\n"
                         "    ]\n"
                         "  }\n"
                         "]";
