std::string Special = "[\n"
                         "  {\n"
                         "    \"Category\": \"Special\",\n"
                         "    \"Items\": [\n"
                         "      {\n"
                         "        \"itemId\": 202023,\n"
                         "        \"itemClass\": \"BP_Pistol_FlareGun_Wrapper_C_1\",\n"
                         "        \"itemName\": \"Esp Flare Gun\",\n"
                         "        \"itemTextColor\": \"0xFF9FBD1C\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      }\n"
                         "    ]\n"
                         "  }\n"
                         "]";
