std::string Sub = "[\n"
                         "  {\n"
                         "    \"Category\": \"Sub-MachineGun\",\n"
                         "    \"Items\": [\n"
                         "      {\n"
                         "        \"itemId\": 102001,\n"
                         "        \"itemClass\": \"BP_MachineGun_Uzi_Wrapper_C_1\",\n"
                         "        \"itemName\": \"UZI\",\n"
                         "        \"itemTextColor\": \"0xFF919AFF\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 102002,\n"
                         "        \"itemClass\": \"BP_MachineGun_UMP9_Wrapper_C_1\",\n"
                         "        \"itemName\": \"UMP45\",\n"
                         "        \"itemTextColor\": \"0xFFF8FAB9\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 102003,\n"
                         "        \"itemClass\": \"BP_MachineGun_Vector_Wrapper_C_1\",\n"
                         "        \"itemName\": \"Vector\",\n"
                         "        \"itemTextColor\": \"0xFF919AFF\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 102004,\n"
                         "        \"itemClass\": \"BP_MachineGun_TommyGun_Wrapper_C_1\",\n"
                         "        \"itemName\": \"Tompson SMG\",\n"
                         "        \"itemTextColor\": \"0xFFF8FAB9\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"           
                         "      }\n"
                         "    ]\n"
                         "  }\n"
                         "]";
