#pragma once

// Pubg Mobile Battelgrounds (2.9.0) SDK Generated By @hhamk2 
// 𝚃𝚎𝚕𝚎𝚐𝚛𝚊𝚖 -: @SANSERO_MOD_1
namespace SDK
{
// UserDefinedStruct BP_STRUCT_LocalizeRes_type.BP_STRUCT_LocalizeRes_type
// 0x0014
struct FBP_STRUCT_LocalizeRes_type
{
	unsigned char UnknownData[0x14];
};

// UserDefinedStruct BP_STRUCT_CameraPostProcessSettings_type.BP_STRUCT_CameraPostProcessSettings_type
// 0x0120
struct FBP_STRUCT_CameraPostProcessSettings_type
{
	unsigned char UnknownData[0x120];
};

}

