#pragma once

// Pubg Mobile Battelgrounds (2.9.0) SDK Generated By @hhamk2 
// 𝚃𝚎𝚕𝚎𝚐𝚛𝚊𝚖 -: @SANSERO_MOD_1
#include "../SDK.hpp"

namespace SDK
{
//---------------------------------------------------------------------------
//Parameters
//---------------------------------------------------------------------------

// Function DBGame.BackpackComponentDBZ.ServerExchangeItemPos
struct UBackpackComponentDBZ_ServerExchangeItemPos_Params
{
	struct FItemDefineID                               DefineID1;                                                // (ConstParm, Parm, ReferenceParm)
	struct FItemDefineID                               DefineID2;                                                // (ConstParm, Parm, ReferenceParm)
};

// Function DBGame.BackpackComponentDBZ.ReceiveItemListDBZ
struct UBackpackComponentDBZ_ReceiveItemListDBZ_Params
{
};

// Function DBGame.BackpackComponentDBZ.OnRep_ItemListNetDBZ
struct UBackpackComponentDBZ_OnRep_ItemListNetDBZ_Params
{
};

// Function DBGame.BackpackComponentDBZ.NotifyItemUpdated
struct UBackpackComponentDBZ_NotifyItemUpdated_Params
{
	struct FItemDefineID                               DefineID;                                                 // (ConstParm, Parm, OutParm, ReferenceParm)
};

// Function DBGame.BackpackComponentDBZ.NotifyItemRemoved
struct UBackpackComponentDBZ_NotifyItemRemoved_Params
{
	struct FItemDefineID                               DefineID;                                                 // (ConstParm, Parm, OutParm, ReferenceParm)
};

// Function DBGame.BackpackComponentDBZ.NotifyItemListUpdated
struct UBackpackComponentDBZ_NotifyItemListUpdated_Params
{
};

// Function DBGame.BackpackComponentDBZ.GetWeaponAttachType
struct UBackpackComponentDBZ_GetWeaponAttachType_Params
{
	int                                                weaponattachID;                                           // (Parm, ZeroConstructor, IsPlainOldData)
	EWeaponAttachmentSocketType                        ReturnValue;                                              // (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData)
};

// Function DBGame.BackpackComponentDBZ.GetWeaponAttachSameType
struct UBackpackComponentDBZ_GetWeaponAttachSameType_Params
{
	int                                                weaponattachID1;                                          // (Parm, ZeroConstructor, IsPlainOldData)
	int                                                weaponattachID2;                                          // (Parm, ZeroConstructor, IsPlainOldData)
	bool                                               ReturnValue;                                              // (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData)
};

// Function DBGame.BackpackComponentDBZ.GetSameTypeSupperWeaponAttachNum
struct UBackpackComponentDBZ_GetSameTypeSupperWeaponAttachNum_Params
{
	int                                                weaponattachID;                                           // (Parm, ZeroConstructor, IsPlainOldData)
	int                                                ReturnValue;                                              // (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData)
};

// Function DBGame.BackpackDBZEquiptHandle.HandlePickup
struct UBackpackDBZEquiptHandle_HandlePickup_Params
{
	TScriptInterface<class UItemContainerInterface>    ItemContainer;                                            // (ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData)
	struct FBattleItemPickupInfo                       PickupInfo;                                               // (Parm)
	EBattleItemPickupReason                            Reason;                                                   // (Parm, ZeroConstructor, IsPlainOldData)
	bool                                               ReturnValue;                                              // (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData)
};

// Function DBGame.BackpackDBZUtils.UnRegisterInvokeClass
struct UBackpackDBZUtils_UnRegisterInvokeClass_Params
{
};

// Function DBGame.BackpackDBZUtils.SetIsNeedInitTable
struct UBackpackDBZUtils_SetIsNeedInitTable_Params
{
	bool                                               IsNeedInit;                                               // (Parm, ZeroConstructor, IsPlainOldData)
};

// Function DBGame.BackpackDBZUtils.RegisterInvokeClass
struct UBackpackDBZUtils_RegisterInvokeClass_Params
{
};

// Function DBGame.BackpackDBZUtils.RealGetBPUtils
struct UBackpackDBZUtils_RealGetBPUtils_Params
{
	class UBackpackBlueprintDBZUtils*                  ReturnValue;                                              // (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData)
};

// Function DBGame.BackpackDBZUtils.PickupFromGround
struct UBackpackDBZUtils_PickupFromGround_Params
{
	class UBackpackComponent*                          BackpackComp;                                             // (Parm, ZeroConstructor, InstancedReference, IsPlainOldData)
	class APickUpWrapperActor*                         Source;                                                   // (Parm, ZeroConstructor, IsPlainOldData)
	struct FBattleItemUseTarget                        AutoEquipTarget;                                          // (Parm)
	bool                                               bForceAutoEquip;                                          // (Parm, ZeroConstructor, IsPlainOldData)
	int                                                pickCount;                                                // (Parm, ZeroConstructor, IsPlainOldData)
	EBattleItemClientPickupType                        BattleItemClientPickupType;                               // (Parm, ZeroConstructor, IsPlainOldData)
};

// Function DBGame.BackpackDBZUtils.GetWeaponAttachHightLevelId
struct UBackpackDBZUtils_GetWeaponAttachHightLevelId_Params
{
	class UBackpackComponent*                          BackpackComp;                                             // (Parm, ZeroConstructor, InstancedReference, IsPlainOldData)
	int                                                attach1;                                                  // (Parm, ZeroConstructor, IsPlainOldData)
	int                                                attach2;                                                  // (Parm, ZeroConstructor, IsPlainOldData)
	int                                                ReturnValue;                                              // (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData)
};

// Function DBGame.BackpackDBZUtils.GetDBZEquipmentType
struct UBackpackDBZUtils_GetDBZEquipmentType_Params
{
	int                                                ReturnValue;                                              // (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData)
};

// Function DBGame.BackpackDBZUtils.GetAvatarRealDefineID
struct UBackpackDBZUtils_GetAvatarRealDefineID_Params
{
	struct FItemDefineID                               DefineID;                                                 // (Parm)
	struct FItemDefineID                               ReturnValue;                                              // (Parm, OutParm, ReturnParm)
};

// Function DBGame.BackpackDBZWeaponAttachHandle.HandlePickup
struct UBackpackDBZWeaponAttachHandle_HandlePickup_Params
{
	TScriptInterface<class UItemContainerInterface>    ItemContainer;                                            // (ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData)
	struct FBattleItemPickupInfo                       PickupInfo;                                               // (Parm)
	EBattleItemPickupReason                            Reason;                                                   // (Parm, ZeroConstructor, IsPlainOldData)
	bool                                               ReturnValue;                                              // (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData)
};

// Function DBGame.CustomSpringArmDBZComponent.StopCameraShake
struct UCustomSpringArmDBZComponent_StopCameraShake_Params
{
	class UClass*                                      Shake;                                                    // (Parm, ZeroConstructor, IsPlainOldData)
	bool                                               bImmediately;                                             // (Parm, ZeroConstructor, IsPlainOldData)
};

// Function DBGame.CustomSpringArmDBZComponent.SetFireCameraData
struct UCustomSpringArmDBZComponent_SetFireCameraData_Params
{
	struct FVector                                     socket;                                                   // (Parm, IsPlainOldData)
	struct FVector                                     Target;                                                   // (Parm, IsPlainOldData)
	float                                              SpringArm;                                                // (Parm, ZeroConstructor, IsPlainOldData)
	float                                              AdditiveFov;                                              // (Parm, ZeroConstructor, IsPlainOldData)
};

// Function DBGame.CustomSpringArmDBZComponent.SetDBZCameraDataEnable
struct UCustomSpringArmDBZComponent_SetDBZCameraDataEnable_Params
{
	TEnumAsByte<EDBZCameraDataType>                    CameraDataType;                                           // (Parm, ZeroConstructor, IsPlainOldData)
	bool                                               IsEnable;                                                 // (Parm, ZeroConstructor, IsPlainOldData)
};

// Function DBGame.CustomSpringArmDBZComponent.PlayCameraShake
struct UCustomSpringArmDBZComponent_PlayCameraShake_Params
{
	class UClass*                                      Shake;                                                    // (Parm, ZeroConstructor, IsPlainOldData)
	float                                              Scale;                                                    // (Parm, ZeroConstructor, IsPlainOldData)
};

// Function DBGame.CustomSpringArmDBZComponent.HasActiveDBZCameraOffsetData
struct UCustomSpringArmDBZComponent_HasActiveDBZCameraOffsetData_Params
{
	TEnumAsByte<EDBZCameraDataType>                    InDataType;                                               // (Parm, ZeroConstructor, IsPlainOldData)
	bool                                               ReturnValue;                                              // (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData)
};

// Function DBGame.DBZCharacterEffectComponent.UpdateCharacterParticleEffect
struct UDBZCharacterEffectComponent_UpdateCharacterParticleEffect_Params
{
};

// Function DBGame.DBZCharacterEffectComponent.RefreshCharacterParticleEffects
struct UDBZCharacterEffectComponent_RefreshCharacterParticleEffects_Params
{
	int                                                HeroID;                                                   // (Parm, ZeroConstructor, IsPlainOldData)
};

// Function DBGame.DBZCharacterEffectComponent.CheckCharacterCanPlayEffect
struct UDBZCharacterEffectComponent_CheckCharacterCanPlayEffect_Params
{
	struct FCharacterParticleEffect                    Effect;                                                   // (Parm, OutParm)
	bool                                               ReturnValue;                                              // (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData)
};

// Function DBGame.DBZProjectileBase.VerifyStartLocation
struct ADBZProjectileBase_VerifyStartLocation_Params
{
};

// Function DBGame.DBZProjectileBase.UpdateServerProjectileData
struct ADBZProjectileBase_UpdateServerProjectileData_Params
{
};

// Function DBGame.DBZProjectileBase.UpdateFollowVelocity
struct ADBZProjectileBase_UpdateFollowVelocity_Params
{
	float                                              InDeltaTime;                                              // (Parm, ZeroConstructor, IsPlainOldData)
};

// Function DBGame.DBZProjectileBase.StartFly
struct ADBZProjectileBase_StartFly_Params
{
	struct FVector                                     StartLocation;                                            // (Parm, IsPlainOldData)
	struct FVector                                     InVelocity;                                               // (Parm, IsPlainOldData)
	float                                              InGravityScale;                                           // (Parm, ZeroConstructor, IsPlainOldData)
};

// Function DBGame.DBZProjectileBase.SetTargetActor
struct ADBZProjectileBase_SetTargetActor_Params
{
	class AActor*                                      InTargetActor;                                            // (Parm, ZeroConstructor, IsPlainOldData)
};

// Function DBGame.DBZProjectileBase.RPC_Multicast_OnImpact
struct ADBZProjectileBase_RPC_Multicast_OnImpact_Params
{
	struct FVector                                     InImpactLocation;                                         // (ConstParm, Parm, ReferenceParm, IsPlainOldData)
	EDBZDestroyType                                    InDestroyType;                                            // (Parm, ZeroConstructor, IsPlainOldData)
	float                                              inScale;                                                  // (Parm, ZeroConstructor, IsPlainOldData)
};

// Function DBGame.DBZProjectileBase.RandomRotateFlyDirection
struct ADBZProjectileBase_RandomRotateFlyDirection_Params
{
	struct FVector                                     InOriginalDir;                                            // (ConstParm, Parm, OutParm, ReferenceParm, IsPlainOldData)
	float                                              InMinRadY;                                                // (Parm, ZeroConstructor, IsPlainOldData)
	float                                              InMaxRadY;                                                // (Parm, ZeroConstructor, IsPlainOldData)
	float                                              InMinRadZ;                                                // (Parm, ZeroConstructor, IsPlainOldData)
	float                                              InMaxRadZ;                                                // (Parm, ZeroConstructor, IsPlainOldData)
	struct FVector                                     ReturnValue;                                              // (Parm, OutParm, ReturnParm, IsPlainOldData)
};

// Function DBGame.DBZProjectileBase.PreHandleImpactOnClient
struct ADBZProjectileBase_PreHandleImpactOnClient_Params
{
	struct FHitResult                                  InImpactResult;                                           // (ConstParm, Parm, OutParm, ReferenceParm, IsPlainOldData)
};

// Function DBGame.DBZProjectileBase.OnStartFly
struct ADBZProjectileBase_OnStartFly_Params
{
};

// Function DBGame.DBZProjectileBase.OnRep_TargetActorLocation
struct ADBZProjectileBase_OnRep_TargetActorLocation_Params
{
};

// Function DBGame.DBZProjectileBase.OnRep_TargetActor
struct ADBZProjectileBase_OnRep_TargetActor_Params
{
};

// Function DBGame.DBZProjectileBase.OnRep_DynamicScaleData
struct ADBZProjectileBase_OnRep_DynamicScaleData_Params
{
};

// Function DBGame.DBZProjectileBase.OnProjectileExplodedOutOfTime
struct ADBZProjectileBase_OnProjectileExplodedOutOfTime_Params
{
};

// Function DBGame.DBZProjectileBase.OnProjectileDestroy
struct ADBZProjectileBase_OnProjectileDestroy_Params
{
};

// Function DBGame.DBZProjectileBase.OnInit
struct ADBZProjectileBase_OnInit_Params
{
};

// Function DBGame.DBZProjectileBase.OnImpact
struct ADBZProjectileBase_OnImpact_Params
{
	struct FHitResult                                  InImpactResult;                                           // (ConstParm, Parm, OutParm, ReferenceParm, IsPlainOldData)
};

// Function DBGame.DBZProjectileBase.HandleRespawned
struct ADBZProjectileBase_HandleRespawned_Params
{
};

// Function DBGame.DBZProjectileBase.HandleRecycled
struct ADBZProjectileBase_HandleRecycled_Params
{
};

// Function DBGame.DBZProjectileBase.HandleImpactOnServer
struct ADBZProjectileBase_HandleImpactOnServer_Params
{
	struct FHitResult                                  InImpactResult;                                           // (ConstParm, Parm, OutParm, ReferenceParm, IsPlainOldData)
	EDBZDestroyType                                    InDestroyType;                                            // (Parm, ZeroConstructor, IsPlainOldData)
};

// Function DBGame.DBZProjectileBase.HandleImpactOnClient
struct ADBZProjectileBase_HandleImpactOnClient_Params
{
	struct FVector                                     InImpactLocation;                                         // (ConstParm, Parm, OutParm, ReferenceParm, IsPlainOldData)
	EDBZDestroyType                                    InDestroyType;                                            // (Parm, ZeroConstructor, IsPlainOldData)
	float                                              inScale;                                                  // (Parm, ZeroConstructor, IsPlainOldData)
};

// Function DBGame.DBZProjectileBase.HandleApplyDamage
struct ADBZProjectileBase_HandleApplyDamage_Params
{
	struct FHitResult                                  InImpactResult;                                           // (ConstParm, Parm, OutParm, ReferenceParm, IsPlainOldData)
	struct FVector                                     InHitPoint;                                               // (ConstParm, Parm, OutParm, ReferenceParm, IsPlainOldData)
	EDBZDestroyType                                    InDestroyType;                                            // (Parm, ZeroConstructor, IsPlainOldData)
};

// Function DBGame.DBZProjectileBase.GetWeakNetAdjustStrength
struct ADBZProjectileBase_GetWeakNetAdjustStrength_Params
{
	float                                              InPing;                                                   // (Parm, ZeroConstructor, IsPlainOldData)
	float                                              ReturnValue;                                              // (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData)
};

// Function DBGame.DBZProjectileBase.GetTheNearestActor
struct ADBZProjectileBase_GetTheNearestActor_Params
{
	TArray<class AActor*>                              InActorList;                                              // (ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm)
	class AActor*                                      ReturnValue;                                              // (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData)
};

// Function DBGame.DBZProjectileBase.GetTargetActor
struct ADBZProjectileBase_GetTargetActor_Params
{
	class AActor*                                      ReturnValue;                                              // (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData)
};

// Function DBGame.DBZProjectileBase.GetStartVelocity
struct ADBZProjectileBase_GetStartVelocity_Params
{
	struct FVector                                     ReturnValue;                                              // (Parm, OutParm, ReturnParm, IsPlainOldData)
};

// Function DBGame.DBZProjectileBase.GetOwnerShootWeapon
struct ADBZProjectileBase_GetOwnerShootWeapon_Params
{
	class ASTExtraShootWeapon*                         ReturnValue;                                              // (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData)
};

// Function DBGame.DBZProjectileBase.GetFlyRotationCoefficient
struct ADBZProjectileBase_GetFlyRotationCoefficient_Params
{
	float                                              InDistance;                                               // (Parm, ZeroConstructor, IsPlainOldData)
	float                                              ReturnValue;                                              // (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData)
};

// Function DBGame.DBZProjectileBase.FixRotateFlyDirection
struct ADBZProjectileBase_FixRotateFlyDirection_Params
{
	struct FVector                                     InOriginalDir;                                            // (ConstParm, Parm, OutParm, ReferenceParm, IsPlainOldData)
	float                                              InThetaX;                                                 // (Parm, ZeroConstructor, IsPlainOldData)
	float                                              InThetaY;                                                 // (Parm, ZeroConstructor, IsPlainOldData)
	struct FVector                                     ReturnValue;                                              // (Parm, OutParm, ReturnParm, IsPlainOldData)
};

// Function DBGame.DBZProjectileBase.DetectFollowTarget
struct ADBZProjectileBase_DetectFollowTarget_Params
{
	float                                              InDeltaTime;                                              // (Parm, ZeroConstructor, IsPlainOldData)
};

// Function DBGame.DBZProjectileBase.CheckIsOutOfRange
struct ADBZProjectileBase_CheckIsOutOfRange_Params
{
	struct FVector                                     InCheckLoc;                                               // (Parm, IsPlainOldData)
	bool                                               ReturnValue;                                              // (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData)
};

// Function DBGame.DBZProjectileBase.CheckImpactInLastTrack
struct ADBZProjectileBase_CheckImpactInLastTrack_Params
{
	struct FVector                                     InTraceStartLoc;                                          // (Parm, IsPlainOldData)
	struct FVector                                     InTraceEndLoc;                                            // (Parm, IsPlainOldData)
	bool                                               ReturnValue;                                              // (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData)
};

// Function DBGame.DBZProjectileBase.CauseDamageToActor
struct ADBZProjectileBase_CauseDamageToActor_Params
{
	class AActor*                                      ImpactActor;                                              // (Parm, ZeroConstructor, IsPlainOldData)
};

// Function DBGame.DBZProjectileBase.BPOnStartFly
struct ADBZProjectileBase_BPOnStartFly_Params
{
};

// Function DBGame.DBZProjectileBase.BPDealDamage
struct ADBZProjectileBase_BPDealDamage_Params
{
};

// Function DBGame.DBZProjectileBase.AdjustStartVelocity
struct ADBZProjectileBase_AdjustStartVelocity_Params
{
};

// Function DBGame.DBZShootWeapon.TickStateModifyAttr
struct ADBZShootWeapon_TickStateModifyAttr_Params
{
};

// Function DBGame.DBZShootWeapon.TickDrawDotCrossHairData
struct ADBZShootWeapon_TickDrawDotCrossHairData_Params
{
};

// Function DBGame.DBZShootWeapon.TickAimEffect
struct ADBZShootWeapon_TickAimEffect_Params
{
};

// Function DBGame.DBZShootWeapon.SetIsEnableScopeInFromEntity
struct ADBZShootWeapon_SetIsEnableScopeInFromEntity_Params
{
	bool                                               Enable;                                                   // (Parm, ZeroConstructor, IsPlainOldData)
};

// Function DBGame.DBZShootWeapon.RefreshAimEffectActiveTime
struct ADBZShootWeapon_RefreshAimEffectActiveTime_Params
{
};

// Function DBGame.DBZShootWeapon.RealShootBulletWithoutParam
struct ADBZShootWeapon_RealShootBulletWithoutParam_Params
{
};

// Function DBGame.DBZShootWeapon.RealShootBullet
struct ADBZShootWeapon_RealShootBullet_Params
{
	struct FVector                                     StartLoc;                                                 // (Parm, IsPlainOldData)
	struct FRotator                                    StartRot;                                                 // (Parm, IsPlainOldData)
};

// Function DBGame.DBZShootWeapon.OnRep_RecentCameraInfo
struct ADBZShootWeapon_OnRep_RecentCameraInfo_Params
{
};

// Function DBGame.DBZShootWeapon.OnRep_IsAimEffectValid
struct ADBZShootWeapon_OnRep_IsAimEffectValid_Params
{
};

// Function DBGame.DBZShootWeapon.NotifyServerRecentCameraInfo
struct ADBZShootWeapon_NotifyServerRecentCameraInfo_Params
{
	struct FWeaponCameraInfo                           CameraInfo;                                               // (ConstParm, Parm, ReferenceParm)
};

// Function DBGame.DBZShootWeapon.IsNeedUploadCameraInfo
struct ADBZShootWeapon_IsNeedUploadCameraInfo_Params
{
	bool                                               ReturnValue;                                              // (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData)
};

// Function DBGame.DBZShootWeapon.InserNextBurstShootInterval
struct ADBZShootWeapon_InserNextBurstShootInterval_Params
{
	float                                              interval;                                                 // (Parm, ZeroConstructor, IsPlainOldData)
};

// Function DBGame.DBZShootWeapon.HandleOnRepRecentCameraInfo
struct ADBZShootWeapon_HandleOnRepRecentCameraInfo_Params
{
};

// Function DBGame.DBZShootWeapon.GetNearestAimTarget
struct ADBZShootWeapon_GetNearestAimTarget_Params
{
	class ASTExtraBaseCharacter*                       ReturnValue;                                              // (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData)
};

// Function DBGame.DBZShootWeapon.GetAimingCharacter
struct ADBZShootWeapon_GetAimingCharacter_Params
{
	class ASTExtraBaseCharacter*                       ReturnValue;                                              // (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData)
};

// Function DBGame.DBZShootWeapon.ExitDrawDotCrossHairData
struct ADBZShootWeapon_ExitDrawDotCrossHairData_Params
{
};

// Function DBGame.DBZShootWeapon.EnterDrawDotCrossHairData
struct ADBZShootWeapon_EnterDrawDotCrossHairData_Params
{
	float                                              DeltaTime;                                                // (Parm, ZeroConstructor, IsPlainOldData)
};

// Function DBGame.DBZShootWeapon.CurBulletChangeBroadcast
struct ADBZShootWeapon_CurBulletChangeBroadcast_Params
{
};

// Function DBGame.DBZShootWeapon.ConditionChangeCrossHairColor
struct ADBZShootWeapon_ConditionChangeCrossHairColor_Params
{
};

// Function DBGame.DBZShootWeapon.AddAimEffectActiveTime
struct ADBZShootWeapon_AddAimEffectActiveTime_Params
{
	float                                              ExtraTime;                                                // (Parm, ZeroConstructor, IsPlainOldData)
};

// Function DBGame.PlummetGuideActor.PendingDestroy
struct APlummetGuideActor_PendingDestroy_Params
{
};

// Function DBGame.PlummetGuideActor.CreateNewDecalComponent
struct APlummetGuideActor_CreateNewDecalComponent_Params
{
	struct FName                                       InName;                                                   // (ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData)
	float                                              InSize;                                                   // (Parm, ZeroConstructor, IsPlainOldData)
	class UMaterialInstance*                           InMaterial;                                               // (Parm, ZeroConstructor, IsPlainOldData)
	float                                              InExistsTime;                                             // (Parm, ZeroConstructor, IsPlainOldData)
	class UCustomDecalComponent*                       ReturnValue;                                              // (ExportObject, Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, IsPlainOldData)
};

// Function DBGame.PlummetWarningActor.CreateNewDecalComponent
struct APlummetWarningActor_CreateNewDecalComponent_Params
{
	struct FName                                       InName;                                                   // (ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData)
	float                                              InSize;                                                   // (Parm, ZeroConstructor, IsPlainOldData)
	class UMaterialInstance*                           InMaterial;                                               // (Parm, ZeroConstructor, IsPlainOldData)
	float                                              InExistsTime;                                             // (Parm, ZeroConstructor, IsPlainOldData)
	class UCustomDecalComponent*                       ReturnValue;                                              // (ExportObject, Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, IsPlainOldData)
};

// Function DBGame.PVEProjectileFollow.SetStartLocationForwardOffset
struct APVEProjectileFollow_SetStartLocationForwardOffset_Params
{
	struct FVector                                     StartLocationForwardOffsetWorld;                          // (ConstParm, Parm, OutParm, ReferenceParm, IsPlainOldData)
};

// Function DBGame.PVEProjectileFollow.RPC_Server_UpdateLocationOffset
struct APVEProjectileFollow_RPC_Server_UpdateLocationOffset_Params
{
	struct FVector_NetQuantize10                       LocationOffset;                                           // (Parm)
};

// Function DBGame.PVEProjectileFollow.OnRep_LocationCorrected
struct APVEProjectileFollow_OnRep_LocationCorrected_Params
{
};

// Function DBGame.PVEProjectileRay.ResetHitData
struct APVEProjectileRay_ResetHitData_Params
{
};

// Function DBGame.PVEProjectileRay.OnRadiusScaleDeltaChanged
struct APVEProjectileRay_OnRadiusScaleDeltaChanged_Params
{
};

// Function DBGame.PVEProjectileRay.OnEffectURLChanged
struct APVEProjectileRay_OnEffectURLChanged_Params
{
};

// Function DBGame.PVEProjectileRay.GetOwnerShootWeapon
struct APVEProjectileRay_GetOwnerShootWeapon_Params
{
	class ASTExtraShootWeapon*                         ReturnValue;                                              // (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData)
};

// Function DBGame.PVEProjectileRay.GetElaspedTime
struct APVEProjectileRay_GetElaspedTime_Params
{
	float                                              ReturnValue;                                              // (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData)
};

// Function DBGame.PVEProjectileRay.GetDisplayRadius
struct APVEProjectileRay_GetDisplayRadius_Params
{
	float                                              ReturnValue;                                              // (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData)
};

// Function DBGame.PVEProjectileRay.GetDamage
struct APVEProjectileRay_GetDamage_Params
{
	float                                              ReturnValue;                                              // (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData)
};

// Function DBGame.PVEProjectileRay.GetAvgRadius
struct APVEProjectileRay_GetAvgRadius_Params
{
	float                                              ReturnValue;                                              // (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData)
};

// Function DBGame.PVEProjectileRaysManager.GetRays
struct APVEProjectileRaysManager_GetRays_Params
{
	TEnumAsByte<ENetRole>                              InRole;                                                   // (Parm, ZeroConstructor, IsPlainOldData)
	TArray<class APVEProjectileRay*>                   ReturnValue;                                              // (Parm, OutParm, ZeroConstructor, ReturnParm)
};

// Function DBGame.STBuffAction_RenderCustomDecal.OnTick
struct USTBuffAction_RenderCustomDecal_OnTick_Params
{
	float                                              DeltaTime;                                                // (Parm, ZeroConstructor, IsPlainOldData)
};

// Function DBGame.STBuffAction_RenderCustomDecal.OnExecute
struct USTBuffAction_RenderCustomDecal_OnExecute_Params
{
};

// Function DBGame.STBuffAction_RenderCustomDecal.OnEnd
struct USTBuffAction_RenderCustomDecal_OnEnd_Params
{
};

// Function DBGame.STBuffAction_RenderCustomDecal.CreateNewDecalComponent
struct USTBuffAction_RenderCustomDecal_CreateNewDecalComponent_Params
{
	struct FName                                       InName;                                                   // (ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData)
	float                                              InSize;                                                   // (Parm, ZeroConstructor, IsPlainOldData)
	class UMaterialInstance*                           InMaterial;                                               // (Parm, ZeroConstructor, IsPlainOldData)
	float                                              InExistsTime;                                             // (Parm, ZeroConstructor, IsPlainOldData)
	class UCustomDecalComponent*                       ReturnValue;                                              // (ExportObject, Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, IsPlainOldData)
};

// Function DBGame.STBuffAction_ReplaceJumpAnim.OnExecute
struct USTBuffAction_ReplaceJumpAnim_OnExecute_Params
{
};

// Function DBGame.STBuffAction_ReplaceJumpAnim.OnEnd
struct USTBuffAction_ReplaceJumpAnim_OnEnd_Params
{
};

// Function DBGame.STBuffAction_SetCharacterFallingMovement.OnTick
struct USTBuffAction_SetCharacterFallingMovement_OnTick_Params
{
	float                                              DetalTime;                                                // (Parm, ZeroConstructor, IsPlainOldData)
};

// Function DBGame.STBuffAction_SetCharacterFallingMovement.OnExecute
struct USTBuffAction_SetCharacterFallingMovement_OnExecute_Params
{
};

// Function DBGame.STBuffAction_SetCharacterFallingMovement.OnEnd
struct USTBuffAction_SetCharacterFallingMovement_OnEnd_Params
{
};

// Function DBGame.STBuffAction_SetCharacterFallingMovement.OnDestroy
struct USTBuffAction_SetCharacterFallingMovement_OnDestroy_Params
{
};

// Function DBGame.STExtraDBZAnimInstance.UpdateParam
struct USTExtraDBZAnimInstance_UpdateParam_Params
{
	float                                              DeltaSeconds;                                             // (Parm, ZeroConstructor, IsPlainOldData)
};

// Function DBGame.STExtraDBZAnimInstance.UpdateHeadOverlapped
struct USTExtraDBZAnimInstance_UpdateHeadOverlapped_Params
{
	float                                              DeltaSeconds;                                             // (Parm, ZeroConstructor, IsPlainOldData)
};

// Function DBGame.STExtraDBZAnimInstance.UpdateAttackType
struct USTExtraDBZAnimInstance_UpdateAttackType_Params
{
};

// Function DBGame.STExtraDBZAnimInstance.UpdateAnimCurve
struct USTExtraDBZAnimInstance_UpdateAnimCurve_Params
{
	float                                              DeltaSeconds;                                             // (Parm, ZeroConstructor, IsPlainOldData)
};

// Function DBGame.STExtraDBZAnimInstance.UpdateAimOffset
struct USTExtraDBZAnimInstance_UpdateAimOffset_Params
{
	float                                              DeltaSeconds;                                             // (Parm, ZeroConstructor, IsPlainOldData)
};

// Function DBGame.STExtraDBZAnimInstance.RefreshHeroSpecifiedParam
struct USTExtraDBZAnimInstance_RefreshHeroSpecifiedParam_Params
{
	int                                                HeroID;                                                   // (Parm, ZeroConstructor, IsPlainOldData)
};

// Function DBGame.STExtraDBZAnimInstance.PlayPlayerDeadAnimation
struct USTExtraDBZAnimInstance_PlayPlayerDeadAnimation_Params
{
};

// Function DBGame.STExtraDBZAnimInstance.OnExitLanding
struct USTExtraDBZAnimInstance_OnExitLanding_Params
{
};

// Function DBGame.STExtraDBZAnimInstance.LuaInitializeAnimation
struct USTExtraDBZAnimInstance_LuaInitializeAnimation_Params
{
};

// Function DBGame.STExtraDBZCharacter.UpdateGunADSHiddenPawn
struct ASTExtraDBZCharacter_UpdateGunADSHiddenPawn_Params
{
};

// Function DBGame.STExtraDBZCharacter.ResetCharacter
struct ASTExtraDBZCharacter_ResetCharacter_Params
{
};

// Function DBGame.STExtraDBZCharacter.RefreshHeroSpecifiedParam
struct ASTExtraDBZCharacter_RefreshHeroSpecifiedParam_Params
{
	int                                                NewHeroID;                                                // (Parm, ZeroConstructor, IsPlainOldData)
};

// Function DBGame.STExtraDBZCharacter.MarkAttackFlag
struct ASTExtraDBZCharacter_MarkAttackFlag_Params
{
	bool                                               Flag;                                                     // (Parm, ZeroConstructor, IsPlainOldData)
};

// Function DBGame.STExtraDBZCharacter.GetShouldHardLanding
struct ASTExtraDBZCharacter_GetShouldHardLanding_Params
{
	bool                                               ReturnValue;                                              // (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData)
};

// Function DBGame.STExtraDBZCharacter.GetOneBarrierFreeEnemyInRange
struct ASTExtraDBZCharacter_GetOneBarrierFreeEnemyInRange_Params
{
	float                                              MaxDistance;                                              // (Parm, ZeroConstructor, IsPlainOldData)
	float                                              MaxAngle;                                                 // (Parm, ZeroConstructor, IsPlainOldData)
	class ASTExtraPlayerCharacter*                     ReturnValue;                                              // (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData)
};

// Function DBGame.STExtraDBZCharacter.GetMarkAttackFlag
struct ASTExtraDBZCharacter_GetMarkAttackFlag_Params
{
	float                                              RecentTime;                                               // (Parm, ZeroConstructor, IsPlainOldData)
	bool                                               ReturnValue;                                              // (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData)
};

// Function DBGame.STExtraDBZCharacter.GetEnemyInRange
struct ASTExtraDBZCharacter_GetEnemyInRange_Params
{
	float                                              MaxDistance;                                              // (Parm, ZeroConstructor, IsPlainOldData)
	float                                              MaxAngle;                                                 // (Parm, ZeroConstructor, IsPlainOldData)
	TArray<struct FAimTargetInfo>                      ReturnValue;                                              // (Parm, OutParm, ZeroConstructor, ReturnParm)
};

// Function DBGame.STExtraDBZCharacter.GetDBZDamageScale
struct ASTExtraDBZCharacter_GetDBZDamageScale_Params
{
	class AActor*                                      DamageCauser;                                             // (Parm, ZeroConstructor, IsPlainOldData)
	float                                              ReturnValue;                                              // (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData)
};

// Function DBGame.STExtraDBZCharacter.GetBarrierFreeEnemyInRange
struct ASTExtraDBZCharacter_GetBarrierFreeEnemyInRange_Params
{
	float                                              MaxDistance;                                              // (Parm, ZeroConstructor, IsPlainOldData)
	float                                              MaxAngle;                                                 // (Parm, ZeroConstructor, IsPlainOldData)
	int                                                Num;                                                      // (Parm, ZeroConstructor, IsPlainOldData)
	TArray<class ASTExtraPlayerCharacter*>             ReturnValue;                                              // (Parm, OutParm, ZeroConstructor, ReturnParm)
};

// Function DBGame.STExtraDBZCharacter.BroadcastClientsSimulateEquipmentDamageInfo
struct ASTExtraDBZCharacter_BroadcastClientsSimulateEquipmentDamageInfo_Params
{
	class ASTExtraBaseCharacter*                       DamageCauser;                                             // (Parm, ZeroConstructor, IsPlainOldData)
	float                                              FinalDamage;                                              // (Parm, ZeroConstructor, IsPlainOldData)
	float                                              EquipentReduce;                                           // (Parm, ZeroConstructor, IsPlainOldData)
	bool                                               brokenEquipment;                                          // (Parm, ZeroConstructor, IsPlainOldData)
};

// Function DBGame.STExtraDBZCharacter.AddWeaponGeneralCount
struct ASTExtraDBZCharacter_AddWeaponGeneralCount_Params
{
	int                                                WeaponId;                                                 // (Parm, ZeroConstructor, IsPlainOldData)
	struct FString                                     GenraString;                                              // (Parm, ZeroConstructor)
	float                                              GeneralValue;                                             // (Parm, ZeroConstructor, IsPlainOldData)
	bool                                               Reset;                                                    // (Parm, ZeroConstructor, IsPlainOldData)
};

// Function DBGame.UAESkillAction_CharacterRushForward.HandleOnActorHit
struct UUAESkillAction_CharacterRushForward_HandleOnActorHit_Params
{
	class AActor*                                      SelfActor;                                                // (Parm, ZeroConstructor, IsPlainOldData)
	class AActor*                                      OtherActor;                                               // (Parm, ZeroConstructor, IsPlainOldData)
	struct FVector                                     NormalImpulse;                                            // (Parm, IsPlainOldData)
	struct FHitResult                                  Hit;                                                      // (ConstParm, Parm, OutParm, ReferenceParm, IsPlainOldData)
};

// Function DBGame.UTSkillAppearance_ParticleSystemDBZ.GetPlayRateScale
struct UUTSkillAppearance_ParticleSystemDBZ_GetPlayRateScale_Params
{
	float                                              ReturnValue;                                              // (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData)
};

}

