#pragma once

// Pubg Mobile Battelgrounds (2.9.0) SDK Generated By @hhamk2 
// 𝚃𝚎𝚕𝚎𝚐𝚛𝚊𝚖 -: @SANSERO_MOD_1
namespace SDK
{
//---------------------------------------------------------------------------
//Script Structs
//---------------------------------------------------------------------------

// UserDefinedStruct BP_STRUCT_DomainCfg_type.BP_STRUCT_DomainCfg_type
// 0x0014
struct FBP_STRUCT_DomainCfg_type
{
	struct FString                                     Domain_0_6EFA5580518F51783205A5DB0670ACDE;                // 0x0000(0x0010) (Edit, BlueprintVisible, ZeroConstructor)
	int                                                ID_1_023102C028A97AB12A1E4FB60A9B2624;                    // 0x0010(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
};

}

